# Generated by Django 5.2.2 on 2026-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('credits', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('rdf_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
