# Generated by Django 5.2.2 on 2026-03-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_courseinstance_person_place_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.CharField(max_length=10)),
                ('fair_score', models.FloatField()),
                ('shacl_violations', models.IntegerField()),
                ('sparql_failed', models.IntegerField()),
                ('full_report', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_report', to='api.courseinstance')),
            ],
        ),
    ]
