# Generated by Django 5.2.2 on 2026-05-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_qualityreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
